# Generated by Django 3.2.23 on 2024-01-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('ratings', models.CharField(max_length=250)),
                ('description', models.TextField(default=None)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('user_name', models.CharField(default=None, max_length=25)),
                ('password', models.CharField(default=None, max_length=10)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('total', models.CharField(default=None, max_length=25)),
                ('address', models.TextField(default=None)),
                ('description', models.TextField(default=None)),
                ('is_paid', models.IntegerField(default=1)),
                ('is_rated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=250)),
                ('price', models.CharField(default=None, max_length=25)),
                ('quantity', models.CharField(default=None, max_length=25)),
                ('description', models.TextField(default=None)),
                ('recommendation', models.TextField(default=None)),
                ('image', models.ImageField(default=None, max_length=250, upload_to='product_images/')),
                ('is_enabled', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('user_name', models.CharField(default=None, max_length=25)),
                ('password', models.CharField(default=None, max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
