# Generated by Django 3.2.23 on 2024-01-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRecommendationtionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
