# Generated by Django 3.2.23 on 2024-04-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRecommendationtionApp', '0002_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='book_id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_rated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
